### PR TITLE
Download valid JSON OSCAL from a system component

### PR DESCRIPTION
**Pull request by woodt**

### CODE REVIEW

**Comment by woodt** [comment]
So far, this PR addresses MTC-98.

**Review by gregelin — CHANGES_REQUESTED** [review]
@woodt This looks good. Could you bump `VERSION` and update `CHANGELOG.md`?

Just update VERSION to a higher number, and follow the pattern in `CHANGELOG.md`. This is useful tracking to users and developers new features.

**Comment by gregelin** [comment]
@woodt  ALSO, should we be writing any time of test? Or maybe the tests of downloaded files is a different story (that is OK with me).

**Comment by woodt** [comment]
@gregelin Yes, I will add a simple test to just exercise the download link, and then when the OSCAL is "compliant" I can update it if necessary.  I think unit tests might be sufficient to demonstrate the JSON is as expected.

Which brings me to a question ... assuming that I add the test (and update the VERSION and CHANGELOG docs), would you want to merge this PR with just those changes, or wait until I've also made the OSCAL compliant?

**Comment by gregelin** [comment]
@woodt I'm in favor of merging what we have and iteratively improving the OSCAL compliance.

**Comment by woodt** [comment]
Now generating component OSCAL that is 99.99% valid.  Ready for final review.

**Comment by gregelin** [comment]
@woodt I am getting a strange result. The PR merge page says 24 files will be updated.

But when I pull `component-oscal-json` and have `master` updated, I get this:

```
$ git diff master..component-oscal-json --name-only
CHANGELOG.md
VERSION
controls/tests.py
controls/urls.py
controls/views.py
siteapp/tests.py
templates/systems/element_detail_tabs.html
```

I also tried merging my local `master` into my local `component-oscal-json` and I got the message that everything was up to date.

So I don't want to approve until we understand the file count difference.

Any thoughts?

**Comment by gregelin** [comment]
Ah. Now the repo is much cleaner. Looks great.

**Review by gregelin — APPROVED** [review]
Looks great! I've tested the code locally: automated tests and manually examined the feature.

**Pull request merged**
