### PR TITLE
Fixed loose file permissions for /tmp/environment.json file

### PR DESCRIPTION
**Pull request by bama4**
Changed file permissions of `/tmp/environment.json` to 0600

### CODE REVIEW

**Comment by bama4** [comment]
`pyup.io/safety-ci` will pass once #1054 is merged.

**Comment by gregelin** [comment]
@JoshData @peterkaminski There's a request to modify our Docker file. I believe it is a request to run Docker commands as `root`. Is this request OK to merge?

**Comment by JoshData** [comment]
Some docker environments force the run time user to be a non-root user, and I think we were encouraged to set up containers in a manner that avoided using the root user, so I think this might break those deployments maybe?

**Comment by bama4** [comment]
> Some docker environments force the run time user to be a non-root user, and I think we were encouraged to set up containers in a manner that avoided using the root user, so I think this might break those deployments maybe?

I fixed it. It now uses the `application` user to change the file permissions

**Review by gregelin — APPROVED** [review]
Looks good.

**Pull request merged**
