### PR TITLE
PR template for use with new PRs to standardize descriptions

### PR DESCRIPTION
**Pull request by t-s**
## Description

Fixes issue of not having a PR template previously. This should assist our process moving forward, by letting developers focus on content and not format. Any suggested changes are welcome.

## Type of change

- [x] A devops change
- [x] This change may require a documentation update.

## How Has This Been Tested?

- [x] In testing, I have not noticed issues while reviewing the text. I have reviewed GitHub documentation to ensure this should now show as a PR template.

**Test Configuration**:
* Version, or branch, tested: N/A
* Python version: N/A

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation if applicable
- [x] My changes generate no new warnings in pylint
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have corrected any misspellings
- [x] I do not introduce security vulnerabilities in this change

### CODE REVIEW

**Comment by bama4** [comment]
Looks good. Documentation section at "Git Templates" of https://docs.google.com/document/d/1NQQ8km_RfVwprtNt1RYuo1z1E63lQlmta_D-T2H9dSc should be updated

**Comment by t-s** [comment]
@bama4, thank you I'll do that now

**Comment by t-s** [comment]
Document updated.

**Review by davidpofo — APPROVED** [review]
Just a change to title and missing period

**Review by gregelin — APPROVED** [review]
looks good

**Pull request merged**
