### PR TITLE
Add File Upload Validation and Unit Tests to Discussion File Upload

### PR DESCRIPTION
**Pull request by bama4**
## Description

This PR adds file validation to discussion attachments, and also adds additional testing to file upload

See original request for more details: #1060
Fixes # (#1082, #1058, #1057)

This validation will be generalized and expanded to include the question answer file upload in a later ticket.

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Ran local tests as follows:

**NOTE:** Due to issues with certain pip dependencies and the hash option, this was tested without the `--require-hashes` option for reading the `requirements.txt` file (See #1206)

```
python3 -m venv env
source env/bin/activate
./quickstart.sh
coverage run --source='.' manage.py test discussion
coverage html
```

Open the generated `htmlcov/index.html` file and observe coverage in `discussions/validators.py`.

**Test Configuration**:
* Version, or branch, tested: ma-add_more_auto_tests_file_upload-20201201
* Python version: 3.6.9

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation if applicable
- [x] My changes generate no new warnings in pylint
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have corrected any misspellings
- [x] I do not introduce security vulnerabilities in this change

### CODE REVIEW

**Comment by bama4** [comment]
Unrelated local test errors:
```
======================================================================
ERROR: test_smt_autocomplete (controls.tests.ControlComponentTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adangwa/REPOS/govready-q/controls/tests.py", line 504, in test_smt_autocomplete
    self.create_fill_statement_form("Component 1", "Component body", 'a', 'status_',"Planned", "Component remarks")
  File "/home/adangwa/REPOS/govready-q/controls/tests.py", line 465, in create_fill_statement_form
    self.click_components_tab()
  File "/home/adangwa/REPOS/govready-q/controls/tests.py", line 450, in click_components_tab
    self.browser.find_element_by_partial_link_text("Component Statements").click()
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 462, in find_element_by_partial_link_text
    return self.find_element(by=By.PARTIAL_LINK_TEXT, value=link_text)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"partial link text","selector":"Component Statements"}
  (Session info: chrome=87.0.4280.66)


======================================================================
ERROR: test_questions_media (siteapp.tests.QuestionsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 1172, in test_questions_media
    self.fill_field("#inputctrl", testFilePath)
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 128, in fill_field
    self.browser.find_element_by_css_selector(css_selector).send_keys(text)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: File not found : /home/adangwa/REPOS/govready-q/fixtures/testimage.png
  (Session info: chrome=87.0.4280.66)


======================================================================
FAIL: test_component_download_oscal_json (controls.tests.ComponentUITests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adangwa/REPOS/govready-q/controls/tests.py", line 238, in test_component_download_oscal_json
    self.assertTrue(self.json_download.is_file())
AssertionError: False is not true

----------------------------------------------------------------------
Ran 67 tests in 452.377s

FAILED (failures=1, errors=2)

```

**Comment by bama4** [comment]
Will have to test this without the `--require-hashes` setting for now until #1206 is resolved.

**Comment by bama4** [comment]
This ticket is ready for review. All tests should pass and test coverage for file validator should be 100%

**Review by davidpofo — APPROVED** [review]
LGTM

**Pull request merged**
