### PR TITLE
Da/add projectv UI

### PR DESCRIPTION
**Pull request by davidpofo**

### CODE REVIEW

**Comment by gregelin** [comment]
@davidpofo Was just looking this project branch.
We need to distinguish between the project version that is the iteration of the USER content and the compliance app version which represents the version of the questionnaire. We want to track both the version of the questionnaire (e.g., compliance app) that is active plus a user defined version of the project content.

**Comment by davidpofo** [comment]
> @davidpofo Was just looking this project branch.
> We need to distinguish between the project version that is the iteration of the USER content and the compliance app version which represents the version of the questionnaire. We want to track both the version of the questionnaire (e.g., compliance app) that is active plus a user defined version of the project content.
@gregelin 
gotcha made adjustments to be able to adjust compliance app version & project version. Now there is the compliance app version and the project's version displayed in the same line like so. 
image

**Comment by davidpofo** [comment]
@gregelin added project version comment in project settings. Can edit with the edit form for version, compliance version, and project title.
image

**Comment by gregelin** [comment]
@davidpofo Nice!

**Comment by gregelin** [comment]
Tests are OK. Test failure is a SNYK vulnerability of High, but only a partial fix available.
Issues to fix by upgrading dependencies:

  Upgrade django@3.1.7 to django@3.1.8 to fix
  ✗ Directory Traversal (new) [Low Severity](https://snyk.io/vuln/SNYK-PYTHON-DJANGO-1090612) in django@3.1.7
    introduced by:
    django@3.1.7
    django-bootstrap3@14.2.0 > django@3.1.7
    django-notifications-hq@1.6.0 > django@3.1.7
    djangorestframework@3.12.4 > django@3.1.7


Issues with no direct upgrade or patch:
  ✗ Timing Attack [High Severity](https://snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-1022152) in cryptography@3.4.7
    introduced by:
    cryptography@3.4.7
  No upgrade or patch available

**Pull request merged**
