### PR TITLE
Update change log

### PR DESCRIPTION
**Pull request by gregelin**

### CODE REVIEW

**Comment by JoshData** [comment]
We never released 0.8.3 so we should just change the date on 0.8.3 to today, and move "Add system minimum and recommended software requirements to documentation." to the 0.8.3 list. (The other two are already covered by the 0.8.3. notes.)

**Comment by gregelin** [comment]
In that case, we need to skip version 0.8.3 and go to 0.8.4 because I put in my monthly report to DHS S&T that we  were releasing v08.8.4. I'll update the CHANGELOG and update tag to -rc1.

**Comment by JoshData** [comment]
Roger that. I will merge and try a new build of the docker image in a moment....

**Comment by JoshData** [comment]
I removed the last two bullets because they were redundant....

**Comment by gregelin** [comment]
OK. Are we ready to merge?

**Comment by JoshData** [comment]
Yes, I'll merge now. I'm going to test the build, and after that I can publish the new image to Docker Hub and update our production instance.

**Pull request merged**
