### PR TITLE
Encryption key management fix Fortify

### PR DESCRIPTION
**Pull request by bama4**
This change is for a false positive Fortify finding (#1093). 
The change is to avoid/reduce future false positive Fortify findings for the `Key Management: Hardcoded Encryption Key` category.

The class member `key` for built-in types (such as `QuerySet` related objects) cannot be changed.

**Test Instructions**
Create a fresh python3 virtual environment:
`python3 -m venv <environment-name>`

Activate virtual environment:
`source <environment-name>/bin/activate`

Run `quickstart.sh`. When prompted select 'y' for adding default database populations:
`./quickstart.sh`

After install, run:
`python3 manage.py test`

### CODE REVIEW

**Comment by gregelin** [comment]
@bama4 @peterkaminski @davidpofo I think I understand what @bama4 changes to use `entry` instead of `key` to reduce Fortify and other code scanner false positives.

Before merging PR, I wanted to ask if we felt `entry` was best term or if we should use `k_entry` or another value?

Also, I want run local tests with the code to double check the refactoring (since we do not have all tests operating in CircleCI).

**Comment by bama4** [comment]
Local test results:

```
======================================================================
ERROR: test_discussion (discussion.tests.DiscussionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adangwa/REPOS/govready-q/discussion/tests.py", line 102, in test_discussion
    self._new_project()
  File "/home/adangwa/REPOS/govready-q/discussion/tests.py", line 86, in _new_project
    self.click_element(".app[data-app='project/simple_project'] .view-app")
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 119, in click_element
    elem = self.browser.find_element_by_css_selector(css_selector)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".app[data-app='project/simple_project'] .view-app"}
  (Session info: chrome=87.0.4280.66)

```

**Comment by bama4** [comment]
Error in master after running `python3 manage.py test`:

```
Traceback (most recent call last):
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/django/contrib/messages/api.py", line 21, in add_message
    messages = request._messages
AttributeError: 'WSGIRequest' object has no attribute '_messages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/adangwa/REPOS/govready-q/testmocking/management/commands/add_data.py", line 67, in handle
    call_command('create_and_fill_assessment', '--action-delay', delay, '--count', count)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/adangwa/REPOS/govready-q/testmocking/management/commands/create_and_fill_assessment.py", line 41, in handle
    call_command('add_system', '--username', admin.username, '--org', org_slug)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/adangwa/REPOS/govready-q/testmocking/management/commands/add_system.py", line 25, in handle
    self.client.add_system()
  File "/home/adangwa/REPOS/govready-q/testmocking/web.py", line 93, in add_system
    self.post("/store", {"portfolio":portfolio.id})
  File "/home/adangwa/REPOS/govready-q/testmocking/web.py", line 87, in post
    self._resolve(req)
  File "/home/adangwa/REPOS/govready-q/testmocking/web.py", line 45, in _resolve
    self._use_page(match.func(req, *match.args, **match.kwargs))
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adangwa/REPOS/govready-q/siteapp/views.py", line 367, in apps_catalog
    messages.add_message(request, messages.ERROR, "Please select 'Start a project' to continue.")
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/django/contrib/messages/api.py", line 30, in add_message
    'You cannot add messages without installing '
django.contrib.messages.api.MessageFailure: You cannot add messages without installing django.contrib.messages.middleware.MessageMiddleware
```

**Comment by gregelin** [comment]
@bama4 I fixed the test issue and checked `quickstart.sh`. All working. Also merged latest `master` and updated `requirements.in` and `requirements.txt`.

**Review by gregelin — APPROVED** [review]
Tseted locally. All tests fixed and working. Code reviewed.

**Pull request merged**
