### PR TITLE
Omitting current_group breadcrumb if it is None for the given question

### PR DESCRIPTION
**Pull request by davidpofo**
This address issue #1094

### CODE REVIEW

**Comment by gregelin** [comment]
@davidpofo What about the case of no `current_group`? Should there be an `elseif` portion to your test?

**Review by gregelin — COMMENTED** [review]
@davidpofo What about the case of no current_group? Should there be an elseif portion to your test?

**Comment by davidpofo** [comment]
> @davidpofo What about the case of no current_group? Should there be an elseif portion to your test?

When there is no group assigned to a question it return None as is default earlier for the function `show_question` in the guidedmodules view return `current_group` this script. So instead of a group name it is just None like attached. My conditional is to include the rest of the breadcrumb but avoid producing a None in the path that will confuse users. Is there a default group you were thinking to substitute the None? If so it would be changing that default not adding another conditional in the template.

image

**Comment by gregelin** [comment]
@davidpofo Thanks for the screenshot. The fix makes sense.

**Comment by gregelin** [comment]
@davidpofo Can you please add entry to `CHANGELOG.md` and bump `VERSION`?

**Review by peterkaminski — APPROVED** [review]
lgtm

**Comment by davidpofo** [comment]
Reviewed during PR party #2

**Pull request closed without merging**
