### PR TITLE
Support displaying controls from multiple catalogs in an SSPs document

### PR DESCRIPTION
**Pull request by davidpofo**
Currently, rendered SSPs in HTML and Word formats fail with error when system's selected controls span multiple catalogs.
This PR allows required refractoring to iterate through each catalog's controls in a system's selected controls

### CODE REVIEW

**Comment by davidpofo** [comment]
@gregelin 1. family for Physical Security is not showing up instead uses AC-1's
2. other catalog headers aren't correct when rendering. Missing catalog formatting
3. same control copying statements for rev4 and rev5

**Review by gregelin — APPROVED** [review]
Looks good so far. Any reason this is a draft?

**Comment by gregelin** [comment]
@davidpofo Will look at items you identified.

**Comment by davidpofo** [comment]
Just noting I also made some changes to how a statement is saved with `save_smt` since it was saving a history erroneously multiple times when changing/saving the `statement` object.

**Review by davidpofo — COMMENTED** [review]
pr party draft need to talk to greg about template look and info. @gregelin

**Pull request merged**
