### PR TITLE
Changed fortify false positive password management code (#1097)

### PR DESCRIPTION
**Pull request by bama4**
Fixed fortify hard coded password in testmocking directory to suppress false positive fortify warnings about hard coded password.

### CODE REVIEW

**Comment by gregelin** [comment]
@bama4 @peterkaminski Maybe we should move the entire 'testmocking' application out of GovReady code base. That would avoid the false positive issue.

**Comment by bama4** [comment]
> @bama4 @peterkaminski Maybe we should move the entire 'testmocking' application out of GovReady code base. That would avoid the false positive issue.

My mistake, this is a false positive that should be noted, this fix is not acceptable for resolving this.

**Review by peterkaminski — COMMENTED** [review]
This is a cool fix, but I'm concerned that an assessor might still find this section of code, and along with the base problem of "there's a password in the code", have another issue of "and why did they try to hide it by saying "pwd" instead of "password".

Closing this unmerged, and @bama4 and I think we'll just document this as a false positive.

**Comment by peterkaminski** [comment]
closing unmerged, see review comment

**Pull request closed without merging**
