### PR TITLE
Spelling fix and temporary ignore a software library upgrade breaking tests

### PR DESCRIPTION
**Pull request by gregelin**
This PR corrects a small spelling error in a README file.

Also adds `django-database-storage-backend==0.1.2` to `requirements_txt_checker_ignoreupdates.txt` file to correct the build checks from breaking until we can review the new version and decide to update.

### CODE REVIEW

**Comment by gregelin** [comment]
CircleCI issue reports and issue that needs to be addressed. Does this mean some files have changed that we need to look at?

```
./requirements_txt_checker.sh
--- /tmp/fileru2VEW	2017-11-12 01:54:40.661523914 +0000
+++ /tmp/filebhnq9M	2017-11-12 01:54:40.773521996 +0000
@@ -123,9 +123,9 @@
     --hash=sha256:f09c3dda7706e2db9f65b46a3658f5d3a02dbca243e57993c3f9f727f48190a1
 filemagic==1.6 \
     --hash=sha256:e684359ef40820fe406f0ebc5bf8a78f89717bdb7fed688af68082d991d6dbf3
-fs==2.0.16 \
-    --hash=sha256:005a496854ebc28648a3197ec04426c50608c5a1413a9ce8ce2197b6d4c23c99 \
-    --hash=sha256:0360e137772c28750dbc42608d93f3f0d16949b24795ec33c9aeb39a216d71ba
+fs==2.0.15 \
+    --hash=sha256:05f54c785c707d0dac1c5250d399fd8bd008a46a519b946fa3e99c0126d4b4dd \
+    --hash=sha256:64eb88788db11c1ac45fcd24fe7f4d76c6fade86b4c161cadfa4ec27e4fd12e9
 future==0.16.0 \
     --hash=sha256:e39ced1ab767b5936646cedba8bcce582398233d6a627067d4c6a454c90cfedb
 gitdb2==2.0.3 \

requirements.txt is not in sync. Run requirements_txt_updater.sh.

./requirements_txt_checker.sh returned exit code 1
```

**Comment by JoshData** [comment]
Looks like there's a new release of "fs". If the package that depends on fs doesn't specify a version then the dependency flattening will pull the most recent release. So i guess there are two ways the build will fail due to an upstream new release - this and the explicit check for new upstream releases (which would cover cases where the dep IS pinned).

Seems like this checking may be too fragile for CI.

On November 11, 2017 8:00:33 PM CST, Greg Elin <notifications@github.com> wrote:
>CircleCI issue reports and issue that needs to be addressed. Does this
>mean some files have changed that we need to look at?
>
>```
>./requirements_txt_checker.sh
>--- /tmp/fileru2VEW	2017-11-12 01:54:40.661523914 +0000
>+++ /tmp/filebhnq9M	2017-11-12 01:54:40.773521996 +0000
>@@ -123,9 +123,9 @@
>--hash=sha256:f09c3dda7706e2db9f65b46a3658f5d3a02dbca243e57993c3f9f727f48190a1
> filemagic==1.6 \
>--hash=sha256:e684359ef40820fe406f0ebc5bf8a78f89717bdb7fed688af68082d991d6dbf3
>-fs==2.0.16 \
>-   
>--hash=sha256:005a496854ebc28648a3197ec04426c50608c5a1413a9ce8ce2197b6d4c23c99
>\
>-   
>--hash=sha256:0360e137772c28750dbc42608d93f3f0d16949b24795ec33c9aeb39a216d71ba
>+fs==2.0.15 \
>+   
>--hash=sha256:05f54c785c707d0dac1c5250d399fd8bd008a46a519b946fa3e99c0126d4b4dd
>\
>+   
>--hash=sha256:64eb88788db11c1ac45fcd24fe7f4d76c6fade86b4c161cadfa4ec27e4fd12e9
> future==0.16.0 \
>--hash=sha256:e39ced1ab767b5936646cedba8bcce582398233d6a627067d4c6a454c90cfedb
> gitdb2==2.0.3 \
>
>requirements.txt is not in sync. Run requirements_txt_updater.sh.
>
>./requirements_txt_checker.sh returned exit code 1
>```
>
>-- 
>You are receiving this because your review was requested.
>Reply to this email directly or view it on GitHub:
>https://github.com/GovReady/govready-q/pull/325#issuecomment-343708083

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JoshData** [comment]
The part of this PR about django-database-... is not right. I think your installed packages are not up to date with requirements.txt. We are tracking the latest version of this package (it's one of my libraries that I recently packaged up).

On November 11, 2017 7:54:53 PM CST, Greg Elin <notifications@github.com> wrote:
>This PR corrects a small spelling error in a README file.
>
>Also adds `django-database-storage-backend==0.1.2` to
>`requirements_txt_checker_ignoreupdates.txt` file to correct the build
>checks from breaking until we can review the new version and decide to
>update.
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/GovReady/govready-q/pull/325
>
>-- Commit Summary --
>
>  * Correct spelling error in Schema.md
>  * Merge branch 'master' of github.com:GovReady/govready-q
>* Temporarily add django-database-storage-backend==0.1.2 to
>requirements checker ignore
>
>-- File Changes --
>
>    M Schema.md (2)
>    M requirements_txt_checker_ignoreupdates.txt (1)
>
>-- Patch Links --
>
>https://github.com/GovReady/govready-q/pull/325.patch
>https://github.com/GovReady/govready-q/pull/325.diff
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/GovReady/govready-q/pull/325

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JoshData** [comment]
The django-database-storage issue was actually a problem in CircleCI's cache. It was pulling in the wrong package (maybe I had mis-specified the package name in an earlier commit?). Doing a Rebuild without Cache fixed it in anther branch. So I'm reverting that commit in your branch and then will squash-merge to get a single commit for the spelling error.

**Pull request merged**
