### PR TITLE
Make Python 3.6-3.7 compatible  via package dependencies

### LINKED ISSUE #1206: Dependency Error When Downloading Pip requirements
**Describe the bug as a Story**
An error occurs when running any script that downloads the pip dependencies in the `develop` branch. This includes the `quickstart.sh` script as well as when building docker containers.

**To Reproduce**
1. Create a clean python3 virtual environment (`python3 -m venv env`)
2. Run `./quickstart.sh`
2. See pip error:
```
Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata==3.3.0->-r requirements.txt (line 307))
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typing-extensions>=3.6.4; python_version < "3.8" from https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl#sha256=7cb407020f00f7bfc3cb3e7881628838e69d8f3fcab2f64742a5e76b2f841918 (from importlib-metadata==3.3.0->-r requirements.txt (line 307))
```

**Expected behavior**
When I run `quickstart.sh` and build docker containers, pip should download and install all dependencies without issue.

**Screenshots**
```
Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata==3.3.0->-r requirements.txt (line 307))
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typing-extensions>=3.6.4; python_version < "3.8" from https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl#sha256=7cb407020f00f7bfc3cb3e7881628838e69d8f3fcab2f64742a5e76b2f841918 (from importlib-metadata==3.3.0->-r requirements.txt (line 307))
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser [e.g. chrome, safari]: N/A
 - Virtual Machine? Yes
 - Screen size
 - Python Version: 3.6.9, 3.8
 - pip version: pip 20.3.3 
 - Python Virtual Environment? Yes

## Acceptance criteria 

  GIVEN a clean python virtual environment or docker build,
  WHEN `pip3 install -r requirements.txt` or similar is run,
  THEN all the python packages in `requirements.txt` should install correctly

**Additional context**
Other pip users are having similar issues:
https://github.com/actions/virtual-environments/issues/2245
https://github.com/cjolowicz/hypermodern-python/issues/174

### PR DESCRIPTION
**Pull request by gregelin**
- Fix    #1206 #1424  re: Python 3.6-3.7 compatibility
  - Stay   Python 3.8-3.9 compatible
  - Update related dependency license tracking comments

### CODE REVIEW

**Comment by gregelin** [comment]
@Dav1dV Can you explain how these changes may GovReady Python libraries compatible with Python 3.6 and 3.7 while maintaining compatibility with 3.8 and 3.9? Or does working with Python 3.6 and 3.7 break 3.8 and 3.9?

**Comment by Dav1dV** [comment]
@gregelin This allows 3.6-3.7 in addition to 3.8-3.9:

The primary 3.6-3.7 blocker was the `importlib-metadata==3.4` >2 v. `django-bootstrap3==14.2` on Python <3.8 conflict;
however, since `importlib-metadata` is no longer a project dependency on Python >=3.8
(it's functionality was integrated into Python 3.8),
it can be reverted back to `importlib-metadata==1.7` (latest <2) for Python 3.6-3.7 only,
resolving that 3.6-3.7 conflict.

The only other non-comment change is adding the `typing-extensions==3.7.4.3` Python 3.6-3.7-only `structlog` dependency.

**Comment by gregelin** [comment]
@Dav1dV That explanation helps. Thanks.

**Comment by gregelin** [comment]
I tested this branch with Python 3.6.9 on macOS 10.14.4 running `./install-govready-q.sh` and also `pip install -r requirements.txt` and am getting errors. 

```e.
ERROR: Cannot install -r requirements.txt (line 182) and importlib-metadata==3.3.0 because these package versions have conflicting dependencies.
```

**Comment by gregelin** [comment]
Let's put this on hold and create in the future different installs for different versions of python.

**Comment by Dav1dV** [comment]
@gregelin Pls check your environment & retry 
since the `requirements.txt` herein specifies `importlib-metadata==1.7.0` not `3.3` in your error message
https://github.com/GovReady/govready-q/pull/1454/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R356
& I successfully tested this on 3.6,7,8,9.

🤔
- Did you try in a venv?
- Did you try uninstalling `importlib-metadata` then `pip3 install -r requirements.txt`?

**Comment by gregelin** [comment]
Hmmm....I wonder if I was on the right branch...

**Comment by gregelin** [comment]
Apparently, I tested the wrong branch. The correct branch installed GovReady correctly in 3.6, 3.7, and 3.8. 

I also tested to see if the adjusted packages will still work after upgrading the requirements using `./requirements_txt_updater.sh`. GovReady-Q still correctly installed in python 3.6 after running upgrade.

**Pull request merged**
