### PR TITLE
Refactored Usage of random to use secure secrets module; adjusted spa…

### PR DESCRIPTION
**Pull request by bama4**
**Description**
This pull request fixes the `Insecure Randomness ` Fortify warnings

**Test Instructions**
Run local tests:

```
python3 -m venv env
source env/bin/activate
./quickstart.sh
python3 manage.py test
```

### CODE REVIEW

**Comment by bama4** [comment]
Test results (Failed tests are unrelated to pull request):

```
======================================================================
FAIL: test_invitations (siteapp.tests.GeneralTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 546, in test_invitations
    do_invitation(self.user2.email)
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 515, in do_invitation
    self._accept_invitation(username)
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 373, in _accept_invitation
    self.assertRegex(self.browser.title, "Sign In")
AssertionError: Regex didn't match: 'Sign In' not found in 'Welcome to Compliance Automation - GovReady-Q'

======================================================================
FAIL: test_questions_module (siteapp.tests.QuestionsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 1233, in test_questions_module
    do_submodule("My second answer.")
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 1209, in do_submodule
    self.assertRegex(self.browser.title, "Next Question: Introduction")
AssertionError: Regex didn't match: 'Next Question: Introduction' not found in 'Next Question: module | Test The Module Question Types - GovReady-Q'

----------------------------------------------------------------------
Ran 63 tests in 352.827s

FAILED (failures=2)
Destroying test database for alias 'default'...
```

**Comment by bama4** [comment]
Ran tests again (unrelated fail):

```
======================================================================
FAIL: test_invitations (siteapp.tests.GeneralTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 546, in test_invitations
    do_invitation(self.user2.email)
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 515, in do_invitation
    self._accept_invitation(username)
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 373, in _accept_invitation
    self.assertRegex(self.browser.title, "Sign In")
AssertionError: Regex didn't match: 'Sign In' not found in 'Welcome to Compliance Automation - GovReady-Q'

----------------------------------------------------------------------
Ran 63 tests in 360.119s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

**Comment by davidpofo** [comment]
12/3 PR party will come back to it after regression testing.

**Comment by bama4** [comment]
Unrelated test fail from running local tests
```
======================================================================
ERROR: test_smt_autocomplete (controls.tests.ControlComponentTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adangwa/REPOS/govready-q/controls/tests.py", line 504, in test_smt_autocomplete
    self.create_fill_statement_form("Component 1", "Component body", 'a', 'status_',"Planned", "Component remarks")
  File "/home/adangwa/REPOS/govready-q/controls/tests.py", line 465, in create_fill_statement_form
    self.click_components_tab()
  File "/home/adangwa/REPOS/govready-q/controls/tests.py", line 450, in click_components_tab
    self.browser.find_element_by_partial_link_text("Component Statements").click()
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 462, in find_element_by_partial_link_text
    return self.find_element(by=By.PARTIAL_LINK_TEXT, value=link_text)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"partial link text","selector":"Component Statements"}
  (Session info: chrome=87.0.4280.66)


======================================================================
FAIL: test_component_download_oscal_json (controls.tests.ComponentUITests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adangwa/REPOS/govready-q/controls/tests.py", line 238, in test_component_download_oscal_json
    self.assertTrue(self.json_download.is_file())
AssertionError: False is not true

======================================================================
FAIL: test_questions_module (siteapp.tests.QuestionsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 1245, in test_questions_module
    do_submodule("My second answer.")
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 1221, in do_submodule
    self.assertRegex(self.browser.title, "Next Question: Introduction")
AssertionError: Regex didn't match: 'Next Question: Introduction' not found in 'Next Question: module | Test The Module Question Types - GovReady-Q'

----------------------------------------------------------------------
Ran 66 tests in 480.105s

FAILED (failures=2, errors=1)
Destroying test database for alias 'default'...

```

**Comment by bama4** [comment]
Fixed CHANGELOG.md and VERSION

**Comment by bama4** [comment]
Build is failing because of #1206

**Review by davidpofo — APPROVED** [review]
LGTM

**Comment by bama4** [comment]
Unrelated local test fails:
```
======================================================================
ERROR: test_discussion (discussion.tests.DiscussionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adangwa/REPOS/govready-q/discussion/tests.py", line 240, in test_discussion
    img = self.browser.find_element_by_css_selector('.comment[data-id="4"] .comment-text p img')
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/adangwa/REPOS/govready-q/env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".comment[data-id="4"] .comment-text p img"}
  (Session info: headless chrome=87.0.4280.88)


======================================================================
FAIL: test_invitations (siteapp.tests.GeneralTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 584, in test_invitations
    do_invitation(self.user2.email)
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 555, in do_invitation
    self._accept_invitation(username)
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 417, in _accept_invitation
    invitation_body = self.pop_email().body
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 198, in pop_email
    self.assertTrue(self.has_more_email())
AssertionError: False is not true

----------------------------------------------------------------------
Ran 82 tests in 1527.196s

FAILED (failures=1, errors=1)
```

**Comment by bama4** [comment]
The conflicting changes to the changelog have been resolved and this is ready for review again.

**Comment by sunstonesecure-robert** [comment]
while I understand this is basically to suppress an unnecessary warning, so the following commentary is moot, just in case anyone cares I will note that secrets claims it is better because it uses urandom.  [This is not better, it is different.](https://news.ycombinator.com/item?id=6550256)

on most OS-es the entropy is the same under the covers.

Since [lately RRAND is in the news again](https://nakedsecurity.sophos.com/2020/06/12/intel-patches-chip-flaw-that-could-leak-your-cryptographic-secrets/), arguably use neither for actual crypto use cases. Lava lamps?

**Pull request merged**
