### PR TITLE
Update jquery to 3.5.1, quill to 1.3.7, bootstrap to 3.4.1

### PR DESCRIPTION
**Pull request by bama4**
Updates the following packages per Twistlock scan suggestions:
* jquery to 3.5.1
* quill to 1.3.7
* bootstrap to 3.4.1

### CODE REVIEW

**Comment by bama4** [comment]
`pyup.io/safety-ci` will pass once #1054 is merged.

**Comment by bama4** [comment]
The pyup.io/safety-ci will run successfully once #1063 is merged into master

**Comment by bama4** [comment]
Added update to cryptography, this is ready to merge.

**Review by gregelin — APPROVED** [review]
Looks good. Tests passed. Reviewed by team.

**Pull request merged**
