### PR TITLE
Closes #1547 Display impact level on project page.

### LINKED ISSUE #1547: Display system impact level on project page (206)
As a GovReady user, I'd like to see the system FISMA impact level categorization displayed on the project page, and maybe on every page related to system, project.

### PR DESCRIPTION
**Pull request by gregelin**
Implement impact level as a statement about a system of type "fisma_impact_level"
with imoact level in body. This continues idea that statements are
factual observations about a system.  Statement must be associated
with system.root_element and be consumed by root_element.

### CODE REVIEW

**Review by davidpofo — COMMENTED** [review]
@gregelin  Needs tests. Also it is unclear how a statement that defines Fisma level looks in oscal which would be covered by an automated unit test. I suggest adding a fixture with statement data that would include a fisma level in the body as suggested.

**Comment by gregelin** [comment]
@davidpofo Tests added. Currently the tests just check that content appears; content can be set with a statement in the database and updated for different content to appear.

**Comment by gregelin** [comment]
@davidpofo Also added type enumeration to Statements. This is ready for review and inclusion.

**Review by davidpofo — APPROVED** [review]
lgtm PR party 4/22

**Pull request merged**
